/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRemindersRouteImport } from './routes/dashboard.reminders'
import { Route as DashboardContractsRouteImport } from './routes/dashboard.contracts'
import { Route as DashboardCancellationsRouteImport } from './routes/dashboard.cancellations'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardActivityRouteImport } from './routes/dashboard.activity'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRemindersRoute = DashboardRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContractsRoute = DashboardContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCancellationsRoute = DashboardCancellationsRouteImport.update({
  id: '/cancellations',
  path: '/cancellations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/cancellations': typeof DashboardCancellationsRoute
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/reminders': typeof DashboardRemindersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/cancellations': typeof DashboardCancellationsRoute
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/reminders': typeof DashboardRemindersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/cancellations': typeof DashboardCancellationsRoute
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/reminders': typeof DashboardRemindersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/activity'
    | '/dashboard/analytics'
    | '/dashboard/cancellations'
    | '/dashboard/contracts'
    | '/dashboard/reminders'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/activity'
    | '/dashboard/analytics'
    | '/dashboard/cancellations'
    | '/dashboard/contracts'
    | '/dashboard/reminders'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/activity'
    | '/dashboard/analytics'
    | '/dashboard/cancellations'
    | '/dashboard/contracts'
    | '/dashboard/reminders'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reminders': {
      id: '/dashboard/reminders'
      path: '/reminders'
      fullPath: '/dashboard/reminders'
      preLoaderRoute: typeof DashboardRemindersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contracts': {
      id: '/dashboard/contracts'
      path: '/contracts'
      fullPath: '/dashboard/contracts'
      preLoaderRoute: typeof DashboardContractsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cancellations': {
      id: '/dashboard/cancellations'
      path: '/cancellations'
      fullPath: '/dashboard/cancellations'
      preLoaderRoute: typeof DashboardCancellationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCancellationsRoute: typeof DashboardCancellationsRoute
  DashboardContractsRoute: typeof DashboardContractsRoute
  DashboardRemindersRoute: typeof DashboardRemindersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCancellationsRoute: DashboardCancellationsRoute,
  DashboardContractsRoute: DashboardContractsRoute,
  DashboardRemindersRoute: DashboardRemindersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
